//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbarakaECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProductCons = new HashSet<OrderProductCon>();
        }
    
        public int orderId { get; set; }
        public Nullable<int> amount { get; set; }
        public string shipmentAdress { get; set; }
        public string paymentway { get; set; }
        public string orderState { get; set; }
        public string shipment { get; set; }
        public Nullable<bool> userNotified { get; set; }
        public Nullable<bool> validity { get; set; }
        public int customerId { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<int> adress { get; set; }
        public Nullable<int> CouponId { get; set; }
        public Nullable<int> totalPrice { get; set; }
    
        public virtual Adress Adress1 { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProductCon> OrderProductCons { get; set; }
        public virtual Coupon Coupon { get; set; }
    }
}
