//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbarakaECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishlistCon
    {
        public int nodeId { get; set; }
        public int customerId { get; set; }
        public int productId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
